name: Test
run-name: Testing
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: apt-get docker.io
        run: |
          sudo apt-get remove containerd.io
          sudo apt install docker.io docker-compose -y

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build with docker
        run: docker build -t builder .

      - name: Start an instance
        run: docker run --name test -t builder ls

      - name: Copy log file
        run: docker cp test:/repo/log.txt ./log.txt

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: test_report
          path: /home/runner/work/LR_8/LR_8/log.txt


